### ISSUE TITLE
Crash after maid changing material

### ISSUE THREAD

**Issue by RGHSSS** [firis-games/LittleMaidReengagedFirisPatch#10]
The maid changes the material and puts it in the egg, and riding on the neck will cause the client to crash.

//----------------------------------------------------------------------------
Time: 2/15/20 3:52 PM
Description: Rendering entity in world

java.lang.NoSuchFieldError: field_70154_o
	at mmmlibx.lib.multiModel.model.mc162.ModelLittleMaid_Beverly7.setRotationAngles(ModelLittleMaid_Beverly7.java:440)
	at net.blacklab.lmr.entity.maidmodel.ModelBaseSolo.func_78087_a(ModelBaseSolo.java:109)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:191)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50)
	at net.blacklab.lmr.client.renderer.entity.RenderModelMulti.renderModelMulti(RenderModelMulti.java:104)
	at net.blacklab.lmr.client.renderer.entity.RenderLittleMaid.doRender(RenderLittleMaid.java:398)
	at net.blacklab.lmr.client.renderer.entity.RenderLittleMaid.func_76986_a(RenderLittleMaid.java:24)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.blacklab.lmc.client.event.RenderPlayerEventHandler.doRender(RenderPlayerEventHandler.java:87)
	at net.blacklab.lmc.client.event.RenderPlayerEventHandler.onRenderPlayerEventPost(RenderPlayerEventHandler.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_733_RenderPlayerEventHandler_onRenderPlayerEventPost_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:74)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:849)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:375)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4222)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1593)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by firis-games** [comment]
特定のマルチモデルでエラーが発生する場合はどのモデルを利用しているかを併記して下さい。
今回のエラーはModelLittleMaid_Beverly7を利用して発生していると推測して説明します。
ModelLittleMaid_Beverly7はバージョンごとに利用できるマルチモデルが異なります。
LittleMaidReengagedで利用する場合はlittleMaidMob-Beverly7-190.zipを使ってください。
