### ISSUE TITLE
世界自動生成EntityLittleMaid時ガーム崩潰

### ISSUE THREAD

**Issue by Eviadc** [firis-games/LittleMaidReengagedFirisPatch#46]
我中國人、日本語超初心者。

今、`WorldEntitySpawner`世界自動生成`EntityLittleMaid`時ガーム崩潰、メイド卵生成無理。サーバーのみのバグです。
Crash log下記。
```
[21:11:02] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class net.blacklab.lmr.entity.littlemaid.EntityLittleMaidAvatarMP from class net.blacklab.lmr.entity.littlemaid.EntityLittleMaid
[21:11:02] [Server thread/WARN] []: java.lang.NullPointerException
[21:11:02] [Server thread/WARN] []: 	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaidAvatarMP.func_192039_O(EntityLittleMaidAvatarMP.java:749)
[21:11:02] [Server thread/WARN] []: 	at net.minecraft.server.management.PlayerList.func_192054_h(PlayerList.java:1769)
[21:11:02] [Server thread/WARN] []: 	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:213)
[21:11:02] [Server thread/WARN] []: 	at net.minecraftforge.common.util.FakePlayer.<init>(FakePlayer.java:45)
[21:11:02] [Server thread/WARN] []: 	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaidAvatarMP.<init>(EntityLittleMaidAvatarMP.java:70)
[21:11:02] [Server thread/WARN] []: 	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaidAvatarMP.<init>(EntityLittleMaidAvatarMP.java:75)
[21:11:02] [Server thread/WARN] []: 	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.<init>(EntityLittleMaid.java:397)
[21:11:02] [Server thread/WARN] []: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:11:02] [Server thread/WARN] []: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:11:02] [Server thread/WARN] []: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:11:02] [Server thread/WARN] []: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[21:11:02] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:306)
[21:11:02] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:292)
[21:11:02] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:67)
[21:11:02] [Server thread/WARN] []: 	at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:657)
[21:11:02] [Server thread/WARN] []: 	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:193)
[21:11:02] [Server thread/WARN] []: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:316)
[21:11:02] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:899)
[21:11:02] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[21:11:02] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
[21:11:02] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636)
[21:11:02] [Server thread/WARN] []: 	at java.lang.Thread.run(Thread.java:748)
[21:11:02] [Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'lmreengaged:littlemaid'
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:306) [EntityEntryBuilder$ConstructorFactory.class:git-CatServer-1.12.2-3440193]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:292) [EntityEntryBuilder$ConstructorFactory.class:git-CatServer-1.12.2-3440193]
	at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:67) [EntityEntry.class:git-CatServer-1.12.2-3440193]
	at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:657) [anh$c.class:?]
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:193) [anb.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:316) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:899) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:782) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.setDead(EntityLittleMaid.java:1276) ~[EntityLittleMaid.class:?]
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.<init>(EntityLittleMaid.java:401) ~[EntityLittleMaid.class:?]
	... 15 more
[21:11:02] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[21:11:02] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.world.WorldEntitySpawner = anb = jar:file:/home/minecraft/multicraft/jar/minecraft_server.1.12.2.jar!/anb.class
[21:11:02] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.world.WorldServer = oo = jar:file:/home/minecraft/multicraft/jar/minecraft_server.1.12.2.jar!/oo.class
[21:11:02] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.server.MinecraftServer = net.minecraft.server.MinecraftServer = jar:file:/home/minecraft/multicraft/jar/minecraft_server.1.12.2.jar!/net/minecraft/server/MinecraftServer.class
[21:11:02] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.server.dedicated.DedicatedServer = nz = jar:file:/home/minecraft/multicraft/jar/minecraft_server.1.12.2.jar!/nz.class
[21:11:02] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: java.lang.Thread = java.lang.Thread = jar:file:/home/jdk1.8.0_51/jre/lib/rt.jar!/java/lang/Thread.class
[21:11:02] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:906) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:782) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:201) ~[anb.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:316) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:899) ~[MinecraftServer.class:?]
	... 4 more
[21:11:02] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/minecraft/multicraft/servers/server17347/./crash-reports/crash-2020-07-16_21.11.02-server.txt
[21:11:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
```

コード參照、推測ある

#### １．
Crash log見
```
[21:11:02] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class net.blacklab.lmr.entity.littlemaid.EntityLittleMaidAvatarMP from class net.blacklab.lmr.entity.littlemaid.EntityLittleMaid
[21:11:02] [Server thread/WARN] []: java.lang.NullPointerException
[21:11:02] [Server thread/WARN] []: 	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaidAvatarMP.func_192039_O(EntityLittleMaidAvatarMP.java:749)
...
[21:11:02] [Server thread/WARN] []: 	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.<init>(EntityLittleMaid.java:397)
```
`EntityLittleMaid`初期化時、
https://github.com/firis-games/LittleMaidReengagedFirisPatch/blob/6fa755fab697a389fbbefe98831fbc38966036f2/src/main/java/net/blacklab/lmr/entity/littlemaid/EntityLittleMaid.java#L397
後、
https://github.com/firis-games/LittleMaidReengagedFirisPatch/blob/6fa755fab697a389fbbefe98831fbc38966036f2/src/main/java/net/blacklab/lmr/entity/littlemaid/EntityLittleMaidAvatarMP.java#L68-L78
而後`super(...)`中`getAdvancements()`引用、
https://github.com/firis-games/LittleMaidReengagedFirisPatch/blob/6fa755fab697a389fbbefe98831fbc38966036f2/src/main/java/net/blacklab/lmr/entity/littlemaid/EntityLittleMaidAvatarMP.java#L746-L749
時`this.avatar`未初期設定。`NullPointerException`出現。

#### ２・
`NullPointerException`出現後、
https://github.com/firis-games/LittleMaidReengagedFirisPatch/blob/6fa755fab697a389fbbefe98831fbc38966036f2/src/main/java/net/blacklab/lmr/entity/littlemaid/EntityLittleMaid.java#L394-L403
`catch`中入、
https://github.com/firis-games/LittleMaidReengagedFirisPatch/blob/6fa755fab697a389fbbefe98831fbc38966036f2/src/main/java/net/blacklab/lmr/entity/littlemaid/EntityLittleMaid.java#L1266-L1279
此時`this.maidAvatar`もう`null`だんだ。
二度目`NullPointerException`出現。
Crash log中
```
[21:11:02] [Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'lmreengaged:littlemaid'
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
...
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.setDead(EntityLittleMaid.java:1276) ~[EntityLittleMaid.class:?]
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.<init>(EntityLittleMaid.java:401) ~[EntityLittleMaid.class:?]
	... 15 more
```

`EntityEntryBuilder.java`中`catch`する、
```java
    static abstract class ConstructorFactory<E extends Entity> implements Function<World, E>
    {
        private final Constructor<? extends E> constructor;

        ConstructorFactory(final Class<? extends E> entity)
        {
            this.constructor = ObfuscationReflectionHelper.findConstructor(entity, World.class);
        }

        @Override
        public E apply(final World world)
        {
            try
            {
                return this.constructor.newInstance(world);
            }
            catch (final IllegalAccessException | InstantiationException | InvocationTargetException e)
            {
                FMLLog.log.error("Encountered an exception while constructing entity '{}'", this.describeEntity(), e);
                return null;
            }
        }

        protected abstract String describeEntity();
    }
```
`null`返回`WorldEntitySpawner.java`、
```java 
  try
  {
      entityliving = biome$spawnlistentry.newInstance(worldServerIn);
  }
  catch (Exception exception)
  {
      exception.printStackTrace();
      return j4;
  }

  entityliving.setLocationAndAngles((double)f, (double)i3, (double)f1, worldServerIn.rand.nextFloat() * 360.0F, 0.0F);
```
此時エーロもうキャッチする、`entityliving=null`、`entityliving.setLocationAndAngles(...)`中`NullPointerException`三度目、結果ガーム崩潰。  
```
[21:11:02] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:906) ~[MinecraftServer.class:?]
...
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:201) ~[anb.class:?]
...
```
  
  
EntityLittleMaidAvatarMP.java#L75、#L78
EntityLittleMaid.java#L400、#L401
二項順次修正後、大丈夫と思う  
  
  
変の言語すまんがだ。。。

**Comment by firis-games** [comment]
連絡頂いた事象と類似で起こりえる問題に対応しました。
対応版はver.fp.045でリリース予定です。

commit 981b4abec52258d7deb499fb5f0a4ad6b03eb665
commit 95dc0f704b1a232a913b9d7eb58d33707cd302af
