### ISSUE TITLE
LittleMaidModelProjectについて

### ISSUE THREAD

**Issue by SCh11** [firis-games/LittleMaidReengagedFirisPatch#48]
「開発環境の構築」で、既存のGradleプロジェクトで「プロジェクト・ルート・ディレクトリー」から「LittleMaidModelProject」フォルダを選択して「完了」を押すと、
「Synchronize Gradle projects with workspace failed due to an error configuring Eclipse.
org.eclipse.core.internal.resources.ResourceException: プロジェクト説明が無効です。

プロジェクト説明が無効です。」
という表示が出て先へ進めず、困っています。なにか解決策などありましたら、教えていただきたいです。よろしくお願いします。

以下エラー文です
org.eclipse.buildship.core.GradlePluginsRuntimeException: org.eclipse.core.internal.resources.ResourceException: プロジェクト説明が無効です。
	at org.eclipse.buildship.core.workspace.internal.DefaultWorkspaceOperations.createProject(DefaultWorkspaceOperations.java:128)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.addNewEclipseProjectToWorkspace(SynchronizeGradleBuildOperation.java:287)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeNonWorkspaceProject(SynchronizeGradleBuildOperation.java:270)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleProjectWithWorkspaceProject(SynchronizeGradleBuildOperation.java:179)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.access$000(SynchronizeGradleBuildOperation.java:99)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$1.run(SynchronizeGradleBuildOperation.java:134)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2311)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:131)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:115)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:85)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: org.eclipse.core.internal.resources.ResourceException: プロジェクト説明が無効です。
	at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:170)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:54)
	at org.eclipse.core.internal.resources.Project.create(Project.java:264)
	at org.eclipse.core.internal.resources.Project.create(Project.java:248)
	at org.eclipse.buildship.core.workspace.internal.DefaultWorkspaceOperations.createProject(DefaultWorkspaceOperations.java:113)
	... 15 more

**Comment by firis-games** [comment]
環境構築時に利用したLittleMaidModelProjectのバージョンはどれを使っていますか？
また環境構築の手順や必要なファイルのバージョンは下記のファイルの手順通り実施したという認識で間違いないでしょうか？
https://github.com/firis-games/LittleMaidReengagedFirisPatch/tree/ver.fp.045/LittleMaidModelProject
Forgeのバージョン（2768）やIDEの環境（Pleiades All in One）が異なる場合エラーが発生する可能性がありますのでバージョンが異なる場合は一度揃えてから確認してください。

**Comment by SCh11** [comment]
バージョンを揃え試してみましたが、同じような表示が出てうまくいきません。

環境構築時に利用したバージョンは
・LittleMaidModelProject-8.1.6.141.fp.033
・forge-1.12.2-14.23.5.2768-mdk
・pleiades-4.8.0-java-win-64bit-jre_20180923
です。

**Comment by firis-games** [comment]
こちらでは現象が再現できておりません。
LittleMaidModelProjectは少し構築手順がことなりますが通常のMOD作成と同じ手順でも可能です。
一度普通のMOD環境の構築をお試しください。
（forge-1.12.2-14.23.5.2768-mdkのREADMEに通常の構築手順が記載されています。）
通常MOD環境が構築可能でしたらLittleMaidModelProjectプロジェクトの中にあるsrcフォルダを作ったMOD環境へ上書きすればLittleMaidModelProjectと同等環境を作成できます。
環境依存に関わる部分になるためこれ以上のサポートは難しいです。
