### ISSUE TITLE
fp.048でSVamモデルが使用できない

### ISSUE THREAD

**Issue by matsubalite** [firis-games/LittleMaidReengagedFirisPatch#58]
この度、fp.040からfp.048に更新しましたが、HiFM様のマルチモデル「SVam」が使用できない問題が発生しました。該当モデルはfp.040では正常に動き、選択画面に表示されていましたが、fp.048では選択画面に表示されませんでした。

使用環境
LittleMaidReengaged_FirisPatch-9.2.4.fp.048
LMLibrary-1.0.8
littleMaidMob-KemonoMdl1.6.2d
littleMaidMob-KMExtend1.6.2d4

**Comment by Siolk** [comment]
私もおなじ問題があります  （fp.043からfp.048に更新しました）
[latest.log](https://github.com/firis-games/LittleMaidReengagedFirisPatch/files/5090436/latest.log)

`java.lang.ClassNotFoundException: MaidModelLittleMaid_SVam:classForName_Error:[java.lang.IllegalAccessError: tried to access class MaidModelLittleMaid_SVam$Vertex from class MaidModelLittleMaid_SVam]
	at firis.lmlib.core.LMClassLoader.classForName(LMClassLoader.java:45) ~[LMClassLoader.class:?]
	at firis.lmlib.common.loader.LMMultiModelHandler.loadHandler(LMMultiModelHandler.java:133) [LMMultiModelHandler.class:?]
	at firis.lmlib.common.loader.LMFileLoader.load(LMFileLoader.java:100) [LMFileLoader.class:?]
	at firis.lmlib.LMLibrary.preInit(LMLibrary.java:90) [LMLibrary.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]`

**Comment by firis-games** [comment]
仕様変更に伴いver.fp.045よりマルチモデル・ボイスパックの格納先が変更されています。

ver.fp.044以前
・Minecraftフォルダ/mods/xxxxxx.zip

ver.fp.045以降
・Minecraftフォルダ/LittleMaidResouce/xxxxxx.zip（Minecraftフォルダ/mods/LittleMaidResouceではありません）

ver.fp.045以降でも一部マルチモデルはmods下でもロード可能ですがすべてのモデルをロードしたい場合は
LittleMaidResouceフォルダにマルチモデルを移動して下さい。
また以前Minecraftフォルダ/mods/LittleMaidResouce下に作成されいたcacheファイルや設定ファイルも
Minecraftフォルダ/LittleMaidResouceに生成されるようになっています。

**Comment by matsubalite** [comment]
返信ありがとうございます。指定されたフォルダにマルチモデルを入れた所、無事にSVamモデルも表示されるようになりました。
