### ISSUE TITLE
LittleMaidModelProjectについて

### ISSUE THREAD

**Issue by JagdFeind** [firis-games/LittleMaidReengagedFirisPatch#64]
件名について、二つのバージョンそれぞれで環境を構築し、いろいろやったところそれぞれエラーなどが起きたので、報告もかねて質問しました。
どちらのファイルでも
win10
forge-1.12.2-14.23.5.2768-mdk
pleiades-4.8.0-java-win-64bit-jre_20180923
で環境構築しました。

LittleMaidModelProject-8.1.6.141.fp.033では src/main/java/ にModelLittleMaid_SR2を継承した新しいjavaファイルを作ったのですが、デバッグしてもそのモデルが反映されませんでした。命名規則に則っているはずですが、どうにもうまくいきませんでした。

また、SampleMaidModelにて以下文を追加したモデルをbuildしzip化したものを　LMM fp0.52 を導入した別環境に導入したところ、弓やダイヤ剣などのアイテムを持たせるとメイドさんが透明になってしまいます。

`

	public void setLivingAnimations(IModelCaps pEntityCaps, float par2, float par3, float pRenderPartialTicks) {
		super.setLivingAnimations(pEntityCaps, par2, par3, pRenderPartialTicks);
		try {
			if( (ItemStack)ModelCapsHelper.getCapsValue(pEntityCaps,caps_currentEquippedItem) != null) {
				ItemStack heldItem = (ItemStack)ModelCapsHelper.getCapsValue(pEntityCaps,caps_currentEquippedItem);

				if(Items.BOW == heldItem.getItem()) {
					System.out.println("OK");
				}
			}else {
				throw new NullPointerException();
			}
		}catch(NullPointerException e) {
			return;
		}
	}
`

LittleMaidModelProject-9.3.0.fp.050　の場合はデバッグをしようとすると,
LMLibrary-1.1.0を導入してくださいといった胸のエラーが表示されてしまいます。
試しにそれを導入するともともとあったLMLibraryとかぶるためもともとあった方を削除すると、LMMがもともとあった方を要求してきてエラーになる、といった形でデバッグができません。

自分としては、できる限り最新版に近い環境でデバッグできるモデル開発環境を整えたいです。fp.050のほうではどのようにすればデバッグできるようになるでしょうか

**Comment by firis-games** [comment]
ver.fp.033については環境が手元にないので後程確認しますのでお待ちください。
ver.fp.050版についてですが同梱されているLMLibraryの内部バージョンが1.0.9になっているため起動チェックでエラーとなっているようです。後程こちらの環境を最新のバージョンで作り直したものを作成しますのでお待ちください。
現状の状態でプロジェクト環境を作成する場合はmodsフォルダ下にあるLMLibrary-1.1.0-dev.jarを通常版のLMLibrary-1.1.0.jarと差し替えてから環境構築を0から実施することで構築可能です。

リトルメイドマルチモデルの構築環境についてですがver.fp.033は過去のバージョンの互換性を持っておりver.fp.033環境で作成したマルチモデルは他のLMRで利用可能です。（LMMやLMMXでは利用不可）
ver.fp.050はFirisPatch版独自機能を含んでいるため通常作成した場合はFirisPatch版でしか使用できません。
しかしFirisPatch版では過去のバージョンの互換性を残す方法がありますが手順を公開していません。
必要でしたら公開準備をして公開しますのでお待ちください。

最後になりますが、ver.fp.052でご提示のプログラムがエラーとなる問題ですがcaps_currentEquippedItemで返却する値が直近のバージョンでItemStackからStringに変更されておりおそらくその影響でエラーとなっています。

**Comment by JagdFeind** [comment]
回答していただきありがとうございます。
LittleMaidModelProject-9.3.0.fp.050　の中のLMLibrary-1.1.0-devからLMLibrary-1.1.0に変えたところ、動作しました。また、LittleMaidModelProject-8.1.6.141.fp.033で起きていたようなメイドモデルが反映されないといったことは起こりませんでした。しばらくはLittleMaidModelProject-9.3.0.fp.050の方を使おうと思います。

しかし、環境を変えてもプログラムの方は修正されませんでした。以下はデバッグ環境下で書いたプログラムです。
`

	public void setLivingAnimations(IModelCaps pEntityCaps, float par2, float par3, float pRenderPartialTicks) {
		super.setLivingAnimations(pEntityCaps, par2, par3, pRenderPartialTicks);

		try {
			Object heldItem = ModelCapsHelper.getCapsValue(pEntityCaps,caps_currentEquippedItem);
			String bow = Items.BOW.toString();
			
			System.out.println(heldItem.getClass().getName());
			System.out.println(bow);
			if(bow.equals(heldItem)) {
				System.out.println("OK");
			}	
		}catch(NullPointerException e) {
			return;
		}			
	}
`
デバッグ、本番どちらもforge14,23,5,2854で行っています。
デバッグ環境(LMR_9.3.0.fp.050-dev)の場合、メイドさんに弓を装備させると以下がシステムコンソールに出てきます

[16:51:20] [main/INFO] [STDOUT]: [ModelLittleMaid_SampleMaidModel:setLivingAnimations:78]: net.minecraft.item.ItemStack
[16:51:20] [main/INFO] [STDOUT]: [ModelLittleMaid_SampleMaidModel:setLivingAnimations:79]: net.minecraft.item.ItemBow@4067634b

ModelCapsHelperによって読みだしたcaps_currentEquippedItemのデータ型はどうやらItemStackのようです。
OKとシステムコンソールには出てきませんでしたが、特にエラーなどは発生しませんでした。

しかし、本番(LMR_9.3.2.fp.052)だと弓などのツールを持たせると動作が停止、終了後に以下のエラーを出します。

The game crashed whilst rendering entity in world
Error: java.lang.NoSuchFieldError: BOW
Exit Code: -1

以下はクラッシュレポートです
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 10/16/20 4:51 PM
Description: Rendering entity in world

java.lang.NoSuchFieldError: BOW
	at ModelLittleMaid_SampleMaidModel.setLivingAnimations(ModelLittleMaid_SampleMaidModel.java:76)
	at firis.lmlib.api.client.model.LMModelLittleMaid.func_78086_a(LMModelLittleMaid.java:97)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:190)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50)
	at firis.lmlib.api.client.renderer.LMRenderMultiModel.func_76986_a(LMRenderMultiModel.java:82)
	at firis.lmlib.api.client.renderer.LMRenderMultiModel.func_76986_a(LMRenderMultiModel.java:16)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:849)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ModelLittleMaid_SampleMaidModel.setLivingAnimations(ModelLittleMaid_SampleMaidModel.java:76)
	at firis.lmlib.api.client.model.LMModelLittleMaid.func_78086_a(LMModelLittleMaid.java:97)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:190)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50)
	at firis.lmlib.api.client.renderer.LMRenderMultiModel.func_76986_a(LMRenderMultiModel.java:82)
	at firis.lmlib.api.client.renderer.LMRenderMultiModel.func_76986_a(LMRenderMultiModel.java:16)

-- Entity being rendered --
Details:
	Entity Type: lmreengaged:littlemaid (net.blacklab.lmr.entity.littlemaid.EntityLittleMaid)
	Entity ID: 17
	Entity Name: リトルメイド
	Entity's Exact location: 465.84, 4.00, 246.68
	Entity's Block location: World: (465,4,246), Chunk: (at 1,0,6 in 29,15; contains blocks 464,0,240 to 479,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.06, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.blacklab.lmr.client.renderer.entity.RenderLittleMaid@479b7132
	Location: -1.43,0.00,-0.72 - World: (-2,0,-1), Chunk: (at 14,0,15 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 60.46875
	Delta: 0.07999802
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:849)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Jagdsolid'/26, l='MpServer', x=467.28, y=4.00, z=247.40]]
	Chunk stats: MultiplayerChunkCache: 369, 369
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (452,4,302), Chunk: (at 4,0,14 in 28,18; contains blocks 448,0,288 to 463,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1209865 game time, 2888321 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 6 total; [EntityLittleMaid['リトルメイド'/17, l='MpServer', x=465.84, y=4.00, z=246.68], EntityLittleMaid['リトルメイド'/19, l='MpServer', x=466.29, y=4.00, z=249.29], EntityPlayerSP['Jagdsolid'/26, l='MpServer', x=467.28, y=4.00, z=247.40], EntityLittleMaid['リトルメイド'/21, l='MpServer', x=478.19, y=4.00, z=261.93], EntityLittleMaid['リトルメイド'/23, l='MpServer', x=477.35, y=4.00, z=259.78], EntityChicken['ニワトリ'/13, l='MpServer', x=426.30, y=4.00, z=314.51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 593459656 bytes (565 MB) / 1375731712 bytes (1312 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                                          | Signature                                |
	|:------ |:------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft     | 1.12.2       | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp           | 9.42         | minecraft.jar                                   | None                                     |
	| LCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge         | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | lmlibrary     | 1.1.2        | LMLibrary-1.1.2.jar                             | None                                     |
	| LCHIJA | lmreengaged   | 9.3.2.fp.052 | LittleMaidReengaged_FirisPatch-9.3.2.fp.052.jar | None                                     |
	| LCHIJA | name-wakander | 1.12-1.3.6   | NameWakander-1.12-1.3.6.jar                     | None                                     |

	Loaded coremods (and transformers): 
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 日本語 (日本)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.75
	OpenGlRenderer: GeForce GTX 1070 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

これはマイクラ側の仕様なのでしょうか

**Comment by firis-games** [comment]
ver.fp.050で動作したとのことですのでver.fp.033については対応をスキップします。
ItemStackの扱いを変更したのがLMLibrary ver1.1.1からになりますので本番で利用しているLMLibraryがver1.1.1以上だと記載のエラーが発生します。

IModelCapsの返却値は以下のようになっています。
LMLibrary 1.1.0
・caps_currentEquippedItemの返却値がItemStack
LMLibrary 1.1.1
・caps_currentEquippedItemの返却値がString（アイテムId）

現状の環境を利用する場合は本番での環境をver.fp.050toLMLibrary.1.10に落とす、もしくはver.fp.053で新しい開発用ファイルを公開しますのでそれをお待ちください。

**Comment by firis-games** [comment]
LittleMaidReengaged Firis's Patch ver.fp.053公開に伴い最新版LittleMaidModelProject-9.3.3.fp.053.zipも合わせて公開しました。

**Comment by JagdFeind** [comment]
公開お疲れ様です。
fp.053でプログラムを組んだところ、実現したいことができそうです。
ご対応していただきありがとうございました。
